### ISSUE TITLE
Font for _ _ _ underlines

### ISSUE THREAD

**Issue by FernandoBasso** [Arthaey/anki-cloze-blanks#11]
Tried and loved the plugin. Thanks a LOT!

My question is about the symbols used for the underline stuff. What happens here (arch linux, xfce) is that the underliens get "connected" and I can't see if I should fill in a blank of two, three, four, etc characters.

Should I pick another font? If that is not that path, what else? Perhaps editing the CSS for the card type/close thing?

**Comment by Arthaey** [comment]
I personally like it to look like one long line ("___"), so that's why it looks that way. :)

But it's easy for you to customize it to look more like "_ _ _" instead. Edit ClozeBlanks.py where it says `BLANKS = "_"` and add a space after the underscore, like so: `BLANKS = "_ "`.

(You should probably also update the add-on, as some other changes and cleanup has happened in the meanwhile.)
